### ISSUE TITLE
模型建立的代码

### ISSUE THREAD

**Issue by smallzccc** [Zhihua-PredictionModel/ML-Prediction-Model#1]
大神会上传论文中的其他代码么，想跟着学习下

**Comment by Zhihua-Zhong** [comment]
> 大神会上传论文中的其他代码么，想跟着学习下

更详细的代码，可以给下面的邮箱发邮件：1042381501@qq.com
再具体联络和交流。

More detail about the code in the paper can be obtained by contacting this email: 1042381501@qq.com
for further communication.
